### ISSUE TITLE
Is Storage API in sample notebook referencing pydatalab?

### ISSUE THREAD

**Issue by jagandecapri** [googledatalab/notebooks#97]
Hi,

Is the Storage API referenced in https://github.com/googledatalab/notebooks/blob/master/tutorials/Storage/Storage%20APIs.ipynb follows the API in http://googledatalab.github.io/pydatalab/datalab.storage.html? The source code for this documentation is in https://github.com/googledatalab/pydatalab/tree/v1.1/datalab/storage

If yes, I couldn't find some classes such as `Item`. The error thrown is `AttributeError: 'module' object has no attribute 'Item'`

Code snippet for your reference:

```python
import google.datalab.storage as storage

shared_bucket = storage.Item('BUCKET_NAME', "KEY_NAME")
```

**Comment by yebrahim** [comment]
**tl;dr**: use `storage.Object` instead of `storage.Item`

-----

Please see the [wiki migration guide](https://github.com/googledatalab/pydatalab/wiki/%60datalab%60-to-%60google.datalab%60-Migration-Guide#storage-changes) from `datalab.storage` to `google.datalab.storage`.

You're using the new APIs under `google.datalab` but you're trying to call an obsolete module in the old namespace. The docs link you referred to is for the old namespace, use [this one](http://googledatalab.github.io/pydatalab/google.datalab.storage.html#google.datalab.storage.Object) instead.

**Comment by jagandecapri** [comment]
Thanks @yebrahim
